### ISSUE TITLE
TODO in group meeting

### ISSUE THREAD

**Issue by jaki1234** [annie823/HCI_Rakonto#2]
- [x] Discovery
- [x] Bookshelf
- [x] Have title change depending on what you're looking at (not always "Rakonto")
- [x] Have back button working as expected
- [ ] Have tapping tabs always bring you to the expected place
- [ ] Have icon art, including icon color change to match text change when tab is selected
- [x] Language filtering
- [ ] Book view
